# passenger actions
PASSENGER_JOIN_QUEUE = "PASSENGER_JOIN_QUEUE"
PASSENGER_EMBARK = "PASSENGER_EMBARK"
PASSENGER_DISEMBARK = "PASSENGER_DISEMBARK"
PASSENGER_ABANDON_QUEUE = "PASSENGER_ABANDON_QUEUE"

# bus actions
BUS_MOVE = "BUS_MOVE"

# stop actions
STOP_PASSENGER_JOIN = "STOP_PASSENGER_JOIN"
STOP_REPORT_QUEUE_LENGTH = "STOP_REPORT_QUEUE_LENGTH"
